CREATE DATABASE IF NOT EXISTS school;
USE school;

CREATE TABLE IF NOT EXISTS students(
	doc VARCHAR(16) NOT NULL PRIMARY KEY,
	docType VARCHAR(3) NOT NULL,
	name VARCHAR(150) NOT NULL,
	age VARCHAR(3) NOT NULL
);